defaultBackend:
  enabled: true

controller:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
  service:
    externalTrafficPolicy: Local   

config:
  enable-multi-accept: "false"
